Add pairs for weekly activities.
Subvisual-Academy/center pull request #14
Opened 2023-07-12 16:45 UTC by MFJess

Why:

* We need to implement weekly activities between pairs of users in the Universe.

This change addresses the need by:

* Creating a weekly activity model, migration file and controller.
* Creating a job that generates unique pairs between users. Every user belongs only to one pair.
* Creating a method in the controller to check if the number of users is odd, and if so, check which user is left out.

2023-07-12 17:35 UTC, DavideSilva commented on config/schedule.yml
>    class: "Jobs::CreateWeeklyQuestion"
Make sure you fetch and rebase with the latest changes. I'm pretty sure we changed this line yesterday and this is not up to date

2023-07-13 09:39 UTC, DavideSilva commented on config/schedule.yml
>    class: "Jobs::CreateWeeklyQuestion"
You need to actually pull the changes into `main` after you do the `git fetch`, with either `git rebase` or `git pull` if you have the config that turns a `pull` into a `rebase` (the global git config file in your `$HOME` directory)

Also, you don't need to specify `origin` everywhere, it should work fine without

2023-07-14 10:13 UTC, zamith requested changes

2023-07-14 10:13 UTC, zamith commented on db/migrate/20230713101848_add_default_to_users_left.rb
> +    change_column_default :users, :left, from: nil, to: false
This is trying to change a column that doesn't exist in the `users` table. Where is the migration to add it?

2023-07-14 12:10 UTC, MFJess commented on app/jobs/create_weekly_activity_job.rb
> +    @user_ids = User.all.order("RANDOM()").pluck(:id)
I thought those were used for local variables. Should I delete the `@` then?

2023-07-14 12:11 UTC, MFJess commented on config/routes.rb
> +  get "/leftuser", to: "weekly_activities#left_user"
Yes, we can. It isn't needed, forgot to delete them. I was testing some things.

2023-07-14 12:51 UTC, MFJess commented on db/migrate/20230713101848_add_default_to_users_left.rb
> +    change_column_default :users, :left, from: nil, to: false
I literally don't know what happened to the migration file, it was there but it seems to have been deleted.
But if you look at the schema, the column `left` exists.
How should I proceed?

2023-07-14 13:03 UTC, MFJess commented on app/jobs/create_weekly_activity_job.rb
> +    @user_ids = @user_ids.unshift(@unused_user_id).uniq
The thing is I want the unused user to be in the first place, that's why I'm using `unshift`
I want everything in the list to be random, except the unused user, so, I first order it randomly, and then make sure the unused user is in the first place with `unshift`.
Does this make sense to you? Maybe I misunderstood your question.

2023-07-14 15:35 UTC, zamith commented on db/migrate/20230713101848_add_default_to_users_left.rb
> +    change_column_default :users, :left, from: nil, to: false
You can change this migration to be an `add_column`

2023-07-18 11:54 UTC, MFJess commented on app/jobs/create_weekly_activity_job.rb
> +    @user_ids = @user_ids.unshift(@unused_user_id).uniq
I'm using `uniq` because if I don't, the unshift will put the element in the first place but it won't remove it from where it was originally, so the element will be duplicated.

2023-07-18 11:59 UTC, DavideSilva commented on app/jobs/create_weekly_activity_job.rb
> +    @user_ids = @user_ids.unshift(@unused_user_id).uniq
That would only happen if you keep the query to fetch the users like you currently have. You can change that to something like `User.where(left: false)` to get a list of all the users except the user that got left out.

If you do that, you'll have no need of `uniq`

2023-07-19 12:54 UTC, zamith approved these changes

2023-07-19 15:53 UTC, merged