Get the the answers to a specific question
Subvisual-Academy/center pull request #17
Opened 2023-07-14 12:10 UTC by TiagoPR

Why:

* The frontend needs to display the answers of the specific question.

This change addresses the need by:

* Adding a method to the answers controller where we get the answers to a specific question.

2023-07-14 12:47 UTC, zamith requested changes

2023-07-14 12:47 UTC, zamith commented on config/routes.rb
> +  get "answers/question/:question_id", to: "answers#get_question"
I think we've discussed this before, but let's try to only use RESTful actions

2023-07-14 12:59 UTC, TiagoPR commented on config/routes.rb
> +  get "answers/question/:question_id", to: "answers#get_question"
But this helps the frontend to get the information more easily no? Should I not get the answers to a specific question on the backend and do it on the frontend? But doesn't it make more complicated?

2023-07-14 15:34 UTC, zamith commented on config/routes.rb
> +  get "answers/question/:question_id", to: "answers#get_question"
That was not what I was referring to. You can still have the functionality, but instead of this action, you can have something like `get "questions/:question_id/answers", to: "questions/answers#index"` (the nesting is not mandatory, but in this case might make sense).

If you take advantage of the `resources` it can be done like this:

```ruby
  resources :questions do
    resources :answers, only: [:index], controller: "questions/answers"
  end
```

2023-07-14 16:44 UTC, TiagoPR commented on config/routes.rb
> +  get "answers/question/:question_id", to: "answers#get_question"
Oh ok, I misunderstood, going to do it 👍

2023-07-17 10:59 UTC, zamith requested changes

2023-07-17 16:56 UTC, zamith commented on app/controllers/answers_controller.rb
> +    @answers = Answer.all.where(question_id: params["question_id"])
```suggestion
    @answers = Answer.where(question_id: params["question_id"])
```

You shouldn't need the `all` here. Just by using the `where` it creates the AR query and when you try to use the `@answers` it'll run the query. `all` you use when you really want all.

2023-07-17 16:57 UTC, zamith commented on app/controllers/answers_controller.rb
> +  def get_question
This action should be removed, right?

2023-07-17 16:57 UTC, zamith commented on config/routes.rb
> +  get "/*", to: "application#not_found"
```suggestion
  get "/*path", to: "application#not_found"
```

Remember that this needs a name for the capture

2023-07-17 17:33 UTC, zamith approved these changes

2023-07-18 08:42 UTC, merged