RSpec
Subvisual-Academy/center pull request #18
Opened 2023-07-18 14:22 UTC by TiagoPR

Why:

* Test functionalities more easily and that everything is working. Possibly add it to the workflow.

This change addresses the need by:

* Adding the RSpec gem and setting it up. Creating some tests for the controllers that we have. Having the bin/rspec binstub.

2023-07-19 17:36 UTC, zamith requested changes

2023-07-19 17:36 UTC, zamith commented on spec/controllers/authentication_controller_spec.rb
> +RSpec.describe AuthenticationController, type: :controller do
Controller tests are not great and we usually don't use them, because they skip the router and all middleware. Instead, I think it's best if you look at [requests specs](https://medium.com/@lcriswell/rails-api-request-specs-with-rspec-effeac468c4e).

PS: For now, you are forbidden from using `before`, `let` or `let!`. Later on we can explore why they are usually bad

2023-07-19 17:36 UTC, zamith commented on spec/controllers/questions/answers_controller_spec.rb
> +      user = User.create(email: "email@gmail.com", password: "password")
Take a look at factories with [factory_bot](https://github.com/thoughtbot/factory_bot)

2023-07-19 17:36 UTC, zamith commented on spec/controllers/questions/answers_controller_spec.rb
> +      user = User.create(email: "email@gmail.com", password: "password")
Look at [4 phase tests](https://thoughtbot.com/blog/four-phase-test) and try to have an empty line between each phase in your tests.

2023-07-20 11:22 UTC, TiagoPR commented on spec/controllers/authentication_controller_spec.rb
> +RSpec.describe AuthenticationController, type: :controller do
Now I'm curious why not to use `before`, it seems like it helps not to have to copy code again to test different things, like right now I have two different tests in which I had to do the get two times

2023-07-21 07:32 UTC, zamith commented on spec/controllers/authentication_controller_spec.rb
> +RSpec.describe AuthenticationController, type: :controller do
Yes, and that's exactly the type of use cases where you don't want to use `before`. The `get` is an integral part of the test, meaning you can't understand the test without it. If you move it out, it means that in order to read the test you have to go up and down the file. Now image the file has over 500 lines (which is common), it's really hard to understand a test.

Tests should be optimized for being easy to understand when looking at a single one. If you ever heard the term DRY, for tests you want the opposite. It's ok to repeat yourself if it makes the test clearer. 

If you use `before` and `let` inside of different `context` or `describe` blocks it becomes even messier to read.

To sum up, it looks cool for a blog post when your tests are all one liners, but it makes almost impossible to work with, in my experience.

2023-07-21 07:33 UTC, zamith requested changes
Still not using request specs, right?

2023-07-21 09:39 UTC, TiagoPR commented
> Still not using request specs, right?

I followed the link you sent, didn't fully understand the difference because it still used the controller 🧐

2023-07-21 09:56 UTC, TiagoPR commented
@zamith Ok just saw another article about it, [https://medium.com/just-tech/rspec-controller-or-request-specs-d93ef563ef11](Controller vs Request Specs), going to change it!

2023-07-24 07:12 UTC, zamith requested changes

2023-07-24 07:12 UTC, zamith commented on spec/controllers/questions/answers_controller_spec.rb
> +      post "/auth/login", params: {email: user.email, password: user.password}
This is something you are going to need a lot, so it's best to extract into a helper that returns the token, for example.

2023-07-24 07:12 UTC, zamith commented on spec/controllers/week_question_controller_spec.rb
> +    it "returns a 200" do
Here you can not only change the verb, but also make it more descriptive.

```suggestion
    it "provides the weekly question for the given user" do
```

2023-07-24 07:12 UTC, zamith commented on spec/factories/users.rb
> +    email { "example@gmail.com" }
This should use a [sequence](https://github.com/thoughtbot/factory_bot/blob/main/GETTING_STARTED.md#sequences), no?

2023-07-24 09:15 UTC, TiagoPR commented on spec/controllers/questions/answers_controller_spec.rb
> +      user = create(:user, email: "example2@gmail.com")
I made it specifically because it complained of having another user with that email already because of the unique field. So I used it this way but should I define another factory of another user?

2023-07-24 09:19 UTC, TiagoPR commented on spec/controllers/questions/answers_controller_spec.rb
> +      user = create(:user, email: "example2@gmail.com")
It gave me an error because of email already taken but show saw that was a line I had before of create(:user) and created again another user, yea just forgot to remove and change.

2023-07-24 09:41 UTC, TiagoPR commented on spec/factories/users.rb
> +    email { "example@gmail.com" }
Oh ok! That's perfect, didn't know about it! Thanks

2023-07-24 09:59 UTC, TiagoPR commented on spec/controllers/authentication_controller_spec.rb
> +RSpec.describe "Authentication", type: :request do
I think that if I remove the type if will think to be a controller spec, I think I have my files on the correct path on the `spec/controllers`

2023-07-24 11:14 UTC, TiagoPR commented on spec/controllers/authentication_controller_spec.rb
> +      post "/auth/login", params: {email: user.email, password: user.password}
I've been searching and I'm not really sure how to do it, could you provide an example or a link with more information?

2023-07-24 13:06 UTC, zamith commented on spec/controllers/questions/answers_controller_spec.rb
> +      user = create(:user, email: "example2@gmail.com")
yeah, because of what I said below about sequences.

2023-07-24 13:06 UTC, zamith commented on spec/controllers/authentication_controller_spec.rb
> +RSpec.describe "Authentication", type: :request do
it should be on `spec/requests` I think

2023-07-25 08:46 UTC, TiagoPR commented on spec/controllers/authentication_controller_spec.rb
> +RSpec.describe "Authentication", type: :request do
Yup, it was that

2023-07-25 09:07 UTC, TiagoPR commented on spec/controllers/authentication_controller_spec.rb
> +      post "/auth/login", params: {email: user.email, password: user.password}
Think I got it

2023-07-25 09:18 UTC, zamith commented on config/routes.rb
> +  post "/auth/login", to: "authentication#login", as: "login"
```suggestion
  post "/auth/login", to: "authentication#login", as: :login
```
It's common to use atoms for things that are identifiers, such as hash keys and route names

2023-07-25 09:18 UTC, zamith commented on spec/requests/week_question_controller_spec.rb
> +      header = {"Authorization" => "Bearer #{token}"}
You might consider have the helper return the header, or have another helper that takes a token and returns the headers. If we want to change the header for some reason we'd have to change it in many tests, otherwise.

2023-07-25 09:27 UTC, zamith approved these changes

2023-07-25 09:28 UTC, zamith commented
Don't forget to run the tests on the PRs and main now

2023-07-25 09:29 UTC, merged