Seeds and change question fields
Subvisual-Academy/center pull request #19
Opened 2023-07-19 15:44 UTC by TiagoPR

Why:

* Store the questions we want to display. There was no necessity for a title on the question.

This change addresses the need by:

* Creating multiple questions on the `seeds.rb`. Updating the migration file to only have the `body` field.

2023-07-19 17:28 UTC, zamith requested changes

2023-07-19 17:28 UTC, zamith commented on db/migrate/20230706152247_create_questions.rb
> +      t.text :body
This migration has already run in production, you can't change it. You need a new migration that removes the title and changes the name of the content to body.

2023-07-19 17:33 UTC, TiagoPR commented on db/migrate/20230706152247_create_questions.rb
> +      t.text :body
I can do that, it's just that I was going to drop the database since there's really nothing there and ran the seed with questions that we are not going to use.

2023-07-21 07:34 UTC, zamith commented on db/migrate/20230706152247_create_questions.rb
> +      t.text :body
That's a bad practice to get used to. There's user data there. The Questions you can go to the console and delete. Or you can even delete them from this migration (not ideal, but doable).

2023-07-21 07:35 UTC, zamith approved these changes

2023-07-21 10:43 UTC, merged