Add function to return weekly friend for the frontend.
Subvisual-Academy/center pull request #20
Opened 2023-07-20 10:30 UTC by MFJess

Why:

* Frontend needs an easier way to get the friend of the week of an user.

This change addresses the need by:

* Having a route nested in users to get the friend of a user.
* Creating a Friends controller with a function to return the friend of a user, that will be used in the context of the logged user.

2023-07-21 07:47 UTC, zamith requested changes

2023-07-21 07:47 UTC, zamith commented on config/routes.rb
> +    resources :friends, only: [:index], controller: "users/friends"
A few things here:

1. You are not return a list of things, so this would likely be `show` instead of `index`
2. I don't think there is a need to make this a nested route, especially under users. It'll be tempting to put a lot of things here, because most stuff is related to the user, but I think it is nicer if you can keep stuff not needed. In this case, you can have a `WeeklyFriendController` that does the same thing.

2023-07-21 07:47 UTC, zamith commented on app/controllers/users/friends_controller.rb
> +    current_user = params["user_id"].to_i
There shouldn't be a need for casting this to integer. Rails will take care of it.

2023-07-21 07:47 UTC, zamith commented on app/controllers/users/friends_controller.rb
> +    current_user = params["user_id"].to_i
Also, you already have the notion of `current_user`, either change this to something like `user` or change the API to use the `current_user` and get the `user_id` from there instead of requiring it in the URL.

2023-07-21 07:47 UTC, zamith commented on app/controllers/users/friends_controller.rb
> +    weekly_activity = WeeklyActivity.where("user_1_id = ? OR user_2_id = ?", current_user, current_user).first
```suggestion
    weekly_activity = WeeklyActivity.where(user_1_id: user_id).or(
      WeeklyActivity.where(user_2_id: user_id)
    ).first
```

I personally prefer to use ActiveRecord's API instead of writing SQL as much as possible, but both are fine.

2023-07-21 09:47 UTC, MFJess commented on app/controllers/users/friends_controller.rb
> +    current_user = params["user_id"].to_i
But how can I compare those without casting to integer since one is a string and the other one is an integer. I tried to do that without the `.to_i` but this way the two variables were always different even when they had the same values

2023-07-21 09:59 UTC, MFJess commented on app/controllers/users/friends_controller.rb
> +    weekly_activity = WeeklyActivity.where("user_1_id = ? OR user_2_id = ?", current_user, current_user).first
yes I was also trying to do it that way, but it wasn't working, I was probably typing it wrong.
Also the SQL seemed more simple so I ended up using it. But already changed it :muscle: thanks

2023-07-24 06:42 UTC, zamith commented on Gemfile
> +gem "finishing_moves"
What do you need this for?

2023-07-24 06:42 UTC, zamith commented on config/routes.rb
> +  resources :friends, only: [:show], controller: "weekly_friends"
```suggestion
  resources :weekly_friends, only: [:show], controller: "weekly_friends"
```

Why not this? Is the URL being only `friends` important?

2023-07-24 09:13 UTC, MFJess commented on config/routes.rb
> +  resources :friends, only: [:show], controller: "weekly_friends"
It's not mandatory, it can absolutely be changed. It's just easier to write/read.

2023-07-24 13:05 UTC, zamith approved these changes

2023-07-24 13:05 UTC, zamith commented on spacecenter.code-workspace
> +{
This file should probably be in the gitignore, no?

2023-07-24 13:23 UTC, merged