Display all the weekly questions
Subvisual-Academy/center pull request #29
Opened 2023-07-31 16:44 UTC by TiagoPR

Why:

* Facilitate the process to get the questions that have been the weekly question.

This change addresses the need by:

* Creating a new function on the controller that displays all the weekly questions, as well as the body of the questions, this way there's no need to do two requests on the FE.

2023-07-31 16:47 UTC, TiagoPR commented
Caught a commit from the other branch.. Not sure if I can delete it without breaking anything

2023-08-02 07:35 UTC, zamith requested changes

2023-08-02 07:35 UTC, zamith commented on app/controllers/weekly_questions_controller.rb
> +    render json: ret.to_json
```suggestion
    render json: WeeklyQuestion.all.to_json(include: {question: {only: :body}})
```

If you do `weekly_question.question` ActiveRecord will do the find for you, since you have a `belongs_to` relation in the model, but also, you can tell `to_json` what you want and get rid of the `map` entirely.

It does change the structure of the json output so you need to change the FE as well, but it changes it for the better, honestly.

2023-08-02 08:58 UTC, TiagoPR commented on app/controllers/weekly_questions_controller.rb
> +    render json: ret.to_json
I was trying to do this but didn't manage, thanks!

2023-08-02 09:26 UTC, zamith approved these changes

2023-08-02 09:36 UTC, merged