User controller GET and POST images
Subvisual-Academy/center pull request #40
Opened 2023-08-09 15:42 UTC by TiagoPR

Why:

* Need to fetch the user `profile_pic` and upload to S3.

This change addresses the need by:

* Updating the `create` function with `attach` and `UserSerializer` retrieving the image url.

2023-08-09 16:40 UTC, DavideSilva approved these changes
Reviewed while pair-programming to debug an issue with posting form data to the controller

🚀

2023-08-10 08:17 UTC, zamith requested changes

2023-08-10 08:17 UTC, zamith commented on config/environments/development.rb
> +  config.active_storage.service = :amazon
This should not be changed, right?

2023-08-10 08:17 UTC, zamith commented on app/controllers/users_controller.rb
> +    if user_params[:profile_pic]
Consider extracting this into a helper method

2023-08-10 09:35 UTC, TiagoPR commented on config/environments/development.rb
> +  config.active_storage.service = :amazon
I was testing to see on S3 checking if the links were working

2023-08-10 14:52 UTC, zamith commented on app/controllers/application_controller.rb
> +  def upload_picture(user)
When I say helper method, I was thinking a private method in the controller. This is a bit specific to extract here. 

My rule of thumb is that you only extract to a shared location after you are using it at least 2, preferably 3 times

2023-08-10 14:52 UTC, zamith commented on app/controllers/application_controller.rb
> +    user_params = request.path_parameters
Can't you pass only the profile pic as an argument? That seems to be the only param you are using.

2023-08-10 14:52 UTC, zamith commented on config/environments/development.rb
> +  config.active_storage.service = :amazon
You can run something like this: https://localstack.cloud/

2023-08-10 16:50 UTC, TiagoPR commented on app/controllers/application_controller.rb
> +  def upload_picture(user)
Oh ok 👍

2023-08-10 16:53 UTC, TiagoPR commented on app/controllers/application_controller.rb
> +    user_params = request.path_parameters
But I need the user to do the `user.profile_pic.attach`

2023-08-11 07:08 UTC, zamith commented on app/controllers/application_controller.rb
> +    user_params = request.path_parameters
Right, the user and the profile pic, you don't need the whole `user_params` is what I meant.

2023-08-11 08:21 UTC, TiagoPR commented on app/controllers/application_controller.rb
> +    user_params = request.path_parameters
Done 👍

2023-08-11 09:36 UTC, zamith commented on app/controllers/users_controller.rb
> +    if profile_pic
```suggestion
    return unless profile_pic
```

This way you don't have to worry about it in the rest of the method

2023-08-14 11:09 UTC, merged